import type { CodingLevel } from "./types";

export const CODING_LEVELS: CodingLevel[] = [
  {
    level: 1,
    size: 6,
    start: { row: 2, col: 0, dir: 1 },
    goal: { row: 2, col: 5 },
    walls: [
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 1, col: 3 },
      { row: 3, col: 3 },
      { row: 1, col: 4 },
      { row: 3, col: 4 },
    ],
    maxCommands: 14,
  },
  {
    level: 2,
    size: 6,
    start: { row: 5, col: 0, dir: 0 },
    goal: { row: 0, col: 5 },
    walls: [
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 1, col: 2 },
      { row: 4, col: 3 },
    ],
    maxCommands: 16,
  },
  {
    level: 3,
    size: 6,
    start: { row: 0, col: 0, dir: 2 },
    goal: { row: 5, col: 5 },
    walls: [
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 2, col: 2 },
      { row: 3, col: 3 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
    ],
    maxCommands: 18,
  },
  {
    level: 4,
    size: 6,
    start: { row: 0, col: 5, dir: 3 },
    goal: { row: 5, col: 0 },
    walls: [
      { row: 0, col: 2 },
      { row: 1, col: 2 },
      { row: 2, col: 2 },
      { row: 3, col: 4 },
      { row: 4, col: 4 },
      { row: 5, col: 4 },
    ],
    maxCommands: 20,
  },
  {
    level: 5,
    size: 6,
    start: { row: 3, col: 0, dir: 1 },
    goal: { row: 3, col: 5 },
    walls: [
      { row: 3, col: 2 },
      { row: 2, col: 2 },
      { row: 4, col: 2 },
      { row: 2, col: 3 },
      { row: 4, col: 3 },
      { row: 3, col: 4 },
    ],
    maxCommands: 18,
  },
  {
    level: 6,
    size: 6,
    start: { row: 5, col: 5, dir: 0 },
    goal: { row: 0, col: 0 },
    walls: [
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 2 },
      { row: 1, col: 2 },
      { row: 4, col: 2 },
    ],
    maxCommands: 22,
  },
  {
    level: 7,
    size: 6,
    start: { row: 0, col: 0, dir: 1 },
    goal: { row: 5, col: 5 },
    walls: [
      { row: 0, col: 3 },
      { row: 1, col: 3 },
      { row: 2, col: 3 },
      { row: 3, col: 1 },
      { row: 4, col: 1 },
      { row: 5, col: 1 },
    ],
    maxCommands: 24,
  },
  {
    level: 8,
    size: 6,
    start: { row: 5, col: 0, dir: 0 },
    goal: { row: 0, col: 5 },
    walls: [
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 2, col: 3 },
      { row: 3, col: 3 },
    ],
    maxCommands: 24,
  },
  {
    level: 9,
    size: 6,
    start: { row: 0, col: 5, dir: 2 },
    goal: { row: 5, col: 0 },
    walls: [
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 3, col: 3 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 1, col: 4 },
    ],
    maxCommands: 26,
  },
  {
    level: 10,
    size: 6,
    start: { row: 5, col: 5, dir: 3 },
    goal: { row: 0, col: 0 },
    walls: [
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 4, col: 2 },
      { row: 4, col: 4 },
    ],
    maxCommands: 28,
  },
];

export function getCodingLevel(level: number): CodingLevel {
  return CODING_LEVELS[level - 1] ?? CODING_LEVELS[0];
}
