export const TYPING_GRADES = [1, 2, 3] as const;
export type TypingGrade = (typeof TYPING_GRADES)[number];

export const WORDS_BY_GRADE: Record<TypingGrade, string[]> = {
  1: [
    "mẹ",
    "bố",
    "con",
    "nhà",
    "cây",
    "hoa",
    "mèo",
    "chó",
    "ăn",
    "uống",
    "đi",
    "về",
    "tay",
    "chân",
    "mắt",
    "tai",
    "miệng",
    "bạn",
    "em",
    "anh",
    "chị",
    "cô",
    "thầy",
    "bút",
    "vở",
    "sách",
    "bàn",
    "ghế",
    "cửa",
    "nắng",
  ],
  2: [
    "trường",
    "học sinh",
    "lớp học",
    "bài tập",
    "vui chơi",
    "yêu thương",
    "gia đình",
    "bữa cơm",
    "sáng sớm",
    "chiều tối",
    "mưa rơi",
    "nắng đẹp",
    "cây xanh",
    "con đường",
    "xe đạp",
    "quả cam",
    "quả táo",
    "bông hoa",
    "chim hót",
    "cá bơi",
    "đọc sách",
    "viết chữ",
    "nghe nhạc",
    "vẽ tranh",
    "chạy nhảy",
    "nghỉ ngơi",
    "dậy sớm",
    "đi ngủ",
    "rửa tay",
    "đánh răng",
  ],
  3: [
    "Việt Nam",
    "thủ đô",
    "Hà Nội",
    "thành phố",
    "ngôi nhà",
    "khu phố",
    "công viên",
    "thư viện",
    "bảo tàng",
    "bài hát",
    "câu chuyện",
    "truyện tranh",
    "môn Toán",
    "môn Tiếng Việt",
    "môn Âm nhạc",
    "môn Mỹ thuật",
    "thể dục",
    "sinh hoạt",
    "lễ hội",
    "Tết Nguyên Đán",
    "quê hương",
    "đất nước",
    "biển xanh",
    "núi cao",
    "dòng sông",
    "cánh đồng",
    "nông trại",
    "siêu thị",
    "chợ quê",
    "bạn thân",
  ],
};

export function pickWords(grade: TypingGrade, count: number): string[] {
  const pool = [...WORDS_BY_GRADE[grade]];
  for (let i = pool.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, count);
}
